// js/cards-data.js
// This file is generated by Claude. Replace it with new card data as needed.
export const cardsData = {
  "meta": { "version": 1, "sprache": "de" },
  "themen": [
    {
      "id": "thema-wbl",
      "name": "WBL",
      "karten": [
        {
          "id": "k-001",
          "frage": "Was versteht man unter dem Prinzip der Wirtschaftlichkeit?",
          "antwort": "Mit minimalem Einsatz einen maximalen Nutzen erzielen (Minimal- oder Maximalprinzip).",
          "stichworte": ["Wirtschaftlichkeit", "Minimalprinzip", "Maximalprinzip", "Nutzen"],
          "falschantworten": [
            "Den Gewinn durch Preiserhöhungen maximieren.",
            "Alle Ressourcen vollständig verbrauchen.",
            "Kosten und Erträge stets gleich halten."
          ],
          "schwierigkeit": "mittel"
        },
        {
          "id": "k-002",
          "frage": "Was ist der Unterschied zwischen Aufwand und Kosten?",
          "antwort": "Aufwand ist der wertmäßige Verzehr in der Finanzbuchhaltung (alle Ausgaben), Kosten sind nur der betriebsbezogene Verzehr in der Kostenrechnung.",
          "stichworte": ["Aufwand", "Kosten", "Finanzbuchhaltung", "Kostenrechnung", "betriebsbezogen"],
          "falschantworten": [
            "Aufwand und Kosten sind immer identisch.",
            "Kosten entstehen nur bei Materialverbrauch.",
            "Aufwand bezieht sich nur auf Personalkosten."
          ],
          "schwierigkeit": "schwer"
        },
        {
          "id": "k-003",
          "frage": "Was versteht man unter dem Gläubigerprinzip (Vorsichtsprinzip) in der Buchführung?",
          "antwort": "Vermögen wird eher zu niedrig, Schulden eher zu hoch bewertet, um Gläubiger vor überhöhten Gewinnausschüttungen zu schützen.",
          "stichworte": ["Gläubigerprinzip", "Vorsichtsprinzip", "Vermögen", "Schulden", "Gläubiger"],
          "falschantworten": [
            "Alle Werte werden zum Marktwert angesetzt.",
            "Gewinne werden möglichst hoch ausgewiesen.",
            "Schulden werden immer zum Nominalwert bewertet."
          ],
          "schwierigkeit": "mittel"
        }
      ]
    }
  ]
};
